
globals: ["@global"]
libs: ["@library"]

view_transitions: true
native_css_nesting: true
inline_css: true
heading_ids: true

language: vi

title_template: "Tusss Notes | %s"
og_image: /img/seo/og.webp
author: Xuan Khoa Tu Nguyen
description: I am Tu, a software engineer specialized in web development. And here is my notes for all the knowledge I have learned
port: 2908

# OG image
og: /img/seo/og.webp

theme_color: dark

navigation:
  header:
    - Tusss Notes: /
    - About Me: //xuankhoatu.com/about

  footer:
    - © Xuan Khoa Tu Nguyen: //xuankhoatu.com/about
