
globals: ["@global"]
libs: ["@library"]

view_transitions: true
native_css_nesting: true
inline_css: true

language: vi

title_template: "Tusss Notes | %s"
og_image: /img/og_emma.png
author: Xuan Khoa Tu Nguyen
favicon: /img/favicon.ico
description: I am Tu, a software engineer specialized in web development. And here is my notes for all the knowledge I have learned
port: 2908

# OG image
origin: //notes.xuankhoatu.com
og: /img/og.jpg

header:
  navigation:
    - Tusss Notes: /
    - About Me: //xuankhoatu.com/about

footer:
  copyright:
    - © Xuan Khoa Tu Nguyen: //xuankhoatu.com/about
